# 網站基本設定
title: Formosan.site
email: your@email.com
description: >-
  一個圖像與文字交會的島嶼之站。  
  歡迎來信交流與投稿。

baseurl: "" # 留空，因為你有自己的網域
url: "https://formosan.site" # 請確認你的自定網址，之後 GitHub Pages https 應該會自動套用

language: zh-Hant
theme: minima

# 社群資訊（可選）
twitter_username: ""
github_username: theFormosan
